name: Test uv cache

on:
  workflow_dispatch:
  push:

jobs:
  test:
    # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
    runs-on: ubuntu-22.04
    env:
      FORCE_COLOR: 1
    steps:
      - name: List installed Python version
        # Expects:
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#python
        run: which -a python
      - name: Show Python 3.12 patch
        run: python3 -V
      - name: List cached Python versions
        # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#hosted-tool-cache
        run: ls -l $RUNNER_TOOL_CACHE/Python/
      - name: Cached Python 3.12.5
        # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#hosted-tool-cache
        run: ls -l $RUNNER_TOOL_CACHE/Python/3.12.5
      - name: Cached Python 3.12.5 - run
        # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#hosted-tool-cache
        run: $RUNNER_TOOL_CACHE/Python/3.12.5/bin/python -V
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.9"
      - name: List Python versions with uv
        run: uv python list --offline
      - name: Install Python 3.12
        run: uv python install 3.12 --offline
